# Generated by Django 3.0.3 on 2020-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department_hods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter Your Full Name', max_length=50)),
                ('cnic', models.CharField(help_text='Enter Your Correct CNIC', max_length=15)),
                ('email', models.CharField(help_text='Enter Your Email', max_length=20)),
                ('password', models.CharField(help_text='Enter Your Password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_result_date', models.CharField(max_length=40)),
                ('final_exam_date', models.CharField(max_length=40)),
                ('mid_result_date', models.CharField(max_length=30)),
                ('mid_final_date', models.CharField(max_length=40)),
            ],
        ),
    ]
